# Generated by Django 5.1.5 on 2025-01-17 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['pk'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
